#include "login_system.h"
#include <iostream>
#include <iomanip>
#include <limits>
using namespace std;

// Khởi tạo tổng ví thưởng = 30
int rewardPool;    // Giá trị thực sẽ load từ file (nếu không có file, mặc định 30)

int main() {
    rewardPool = loadRewardPool();
    initPendingChangeFile(); // Khởi tạo file lưu thông tin các thay đổi chờ xác nhận OTP (nếu chưa có)
    srand((unsigned)time(nullptr)); // Khởi tạo seed cho hàm sinh số ngẫu nhiên (dùng cho password, OTP...)
    backupData(); // Sao lưu dữ liệu người dùng sang file dự phòng trước khi xử lý mới
    auto users = loadUsers(); // Đọc toàn bộ danh sách người dùng từ file vào bộ nhớ

    // Kiểm tra nếu chưa có tài khoản admin mặc định thì tạo mới
    if (!findUser(users, "admin")) {
        User a;
        a.username = "admin";                                // Tên đăng nhập mặc định
        a.passwordHash = hashPassword("admin");              // Mật khẩu mặc định là "admin" (lưu dạng băm)
        a.fullName = "Administrator";                        // Họ tên hiển thị cho admin
        a.isAdmin = true;                                    // Đánh dấu là admin
        a.isAutoGenerated = false;                           // Không bắt buộc đổi mật khẩu
        a.wallet.id = string("WAL") + to_string(time(nullptr)); // Sinh id ví duy nhất từ thời gian
        a.wallet.balance = -1;                               // Số dư -1 nghĩa là không giới hạn (admin không bị trừ điểm)
        a.otp = "";
        a.pendingFullName = "";
        a.pendingPasswordHash = "";
        users.push_back(a);                                  // Thêm admin vào danh sách
        saveUsers(users);                                    // Lưu lại file dữ liệu
        cout << "Default admin created: admin / admin\n";
    }

    // Vòng lặp menu chính của chương trình
    while (true) {
        clearScreen(); // Xóa màn hình console cho đẹp
        cout << "=============================================\n";
        cout << "          ACCOUNT MANAGEMENT SYSTEM       \n";
        cout << "=============================================\n\n";
        // In ra menu lựa chọn chính
        cout << left
            << setw(1) << "1." << setw(17) << "Register"   // Đăng ký tài khoản mới
            << setw(1) << "2." << setw(17) << "Login"      // Đăng nhập
            << setw(1) << "0." << "Exit" << '\n';          // Thoát chương trình
        cout << "---------------------------------------------\n";
        cout << "Choice: ";
        int cmd; cin >> cmd; cin.ignore(numeric_limits<streamsize>::max(), '\n');
        switch (cmd) {
        case 1: // Người dùng chọn đăng ký tài khoản mới
            registerUser(users);
            break;
        case 2: { // Người dùng chọn đăng nhập
            User* u = login(users); // Đăng nhập, trả về con trỏ user nếu thành công
            if (u) {
                // Nếu là admin, vào menu admin, ngược lại vào menu người dùng thường
                if (u->isAdmin) adminMenu(u, users);
                else userMenu(u, users);
            }
            break;
        }
        case 0: // Người dùng chọn thoát chương trình
            cout << "Goodbye.\n";
            return 0;
        default: // Người dùng nhập sai lựa chọn
            cout << "Invalid choice.\n";
        }
        // Dừng màn hình chờ người dùng nhấn Enter để trở lại menu chính
        cin.ignore(numeric_limits<streamsize>::max(), '\n');
        cout << "\nPress Enter to return to main menu...";
        cin.get();
    }
    return 0;
}
