#include "login_system.h"
#include <iostream>
#include <iomanip>
#include <limits>
using namespace std;

// Biến toàn cục rewardPool: Tổng số điểm thưởng còn lại (dùng để thưởng user mới)
int rewardPool;    // Sẽ được load từ file khi khởi động chương trình

int main() {
    rewardPool = loadRewardPool();          // Đọc số điểm thưởng từ file (nếu chưa có file, mặc định 30 điểm)
    initPendingChangeFile();                // Đảm bảo file pending_change.txt tồn tại để lưu các thay đổi chờ xác nhận OTP
    srand((unsigned)time(nullptr));         // Khởi tạo seed ngẫu nhiên cho các hàm sinh mật khẩu, OTP...
    backupData();                           // Sao lưu dữ liệu người dùng hiện tại sang file dự phòng (users.bak)
    auto users = loadUsers();               // Đọc toàn bộ danh sách người dùng từ file vào vector

    // Kiểm tra hệ thống đã có tài khoản admin mặc định chưa (username: admin)
    if (!findUser(users, "admin")) {
        // Nếu chưa có thì tạo mới user admin với mật khẩu mặc định "admin"
        User a;
        a.username = "admin";
        a.passwordHash = hashPassword("admin");              // Mật khẩu lưu dạng hash, không lưu thô
        a.fullName = "Administrator";
        a.isAdmin = true;                                   // Đánh dấu là admin
        a.isAutoGenerated = false;                          // Không bắt buộc đổi mật khẩu ngay lần đầu
        a.wallet.id = string("WAL") + to_string(time(nullptr)); // Sinh mã ví dựa trên thời gian hiện tại
        a.wallet.balance = -1;                              // Số dư -1: không giới hạn (admin có thể chuyển không giới hạn)
        a.otp = "";
        a.pendingFullName = "";
        a.pendingPasswordHash = "";
        users.push_back(a);                                 // Thêm admin vào danh sách user
        saveUsers(users);                                   // Lưu lại dữ liệu users.dat
        cout << "Default admin created: admin / admin\n";
    }

    // =========================
    // Menu chính của chương trình
    // =========================
    while (true) {
        clearScreen(); // Xóa màn hình, giao diện gọn gàng
        cout << "=============================================\n";
        cout << "          ACCOUNT MANAGEMENT SYSTEM       \n";
        cout << "=============================================\n\n";
        cout << left
            << setw(1) << "1." << setw(17) << "Register"      // Đăng ký user mới
            << setw(1) << "2." << setw(17) << "Login"         // Đăng nhập tài khoản
            << setw(1) << "0." << "Exit" << '\n';             // Thoát chương trình
        cout << "---------------------------------------------\n";
        cout << "Choice: ";

        int cmd;
        // Nhận lựa chọn chức năng từ người dùng (phải là số)
        if (!(cin >> cmd)) {                                // Nếu nhập lỗi (không phải số)
            cout << "Invalid input! Please enter a number.\n";
            cin.clear(); // Xóa trạng thái lỗi nhập
            cin.ignore(numeric_limits<streamsize>::max(), '\n'); // Xóa các ký tự thừa trong buffer
            cout << "\nPress Enter to return to main menu...";
            cin.get();
            continue;   // Quay lại vòng lặp menu
        }
        cin.ignore(numeric_limits<streamsize>::max(), '\n'); // Bỏ Enter thừa sau khi nhập

        switch (cmd) {
        case 1:
            registerUser(users);                            // Gọi hàm đăng ký user mới
            break;
        case 2: {
            User* u = login(users);                         // Gọi hàm đăng nhập
            if (u) {                                       // Nếu đăng nhập thành công
                if (u->isAdmin) adminMenu(u, users);        // Nếu là admin, mở menu quản trị
                else userMenu(u, users);                    // Nếu là user thường, mở menu người dùng
            }
            break;
        }
        case 0:
            cout << "Goodbye.\n";
            return 0;                                       // Thoát chương trình (kết thúc main)
        default:
            cout << "Invalid choice.\n";                    // Nếu nhập số ngoài phạm vi
        }
        cout << "\nPress Enter to return to main menu...";
        cin.get();                                          // Dừng lại chờ người dùng đọc kết quả
    }

    return 0; // Chương trình kết thúc tại đây (không bao giờ tới vì có return 0 phía trên)
}
