#include <iostream>
#include <fstream>
#include <vector>
#include <sstream>
#include "User.h"
using namespace std;

vector<User> users;

void registerUser() {
    string username, password, name;
    cout << "\nEnter username: "; cin >> username;
    cout << "Enter password (or leave blank to auto-generate): ";
    cin.ignore();
    getline(cin, password);
    cout << "Enter full name: "; getline(cin, name);

    bool autoGen = false;
    if (password.empty()) {
        password = genrateOTP();
        autoGen = true;
        cout << "Generated password: " << password << endl;
    }

    User newUser(username, password, name, false, autoGen);
    users.push_back(newUser);

    // Ghi file: dùng ký tự | phân tách tên để tránh lỗi khi tên có khoảng trắng
    ofstream fout("users.txt", ios::app);
    fout << username << ' ' << newUser.hashedPassword << '|' << name << "| "
        << newUser.isAdmin << ' ' << newUser.isAutogeneratedPassword << '\n';
    fout.close();

    cout << "Registration successful.\n";
}

void loginUser() {
    string username, password;
    cout << "Enter username: "; cin >> username;
    cout << "Enter password: "; cin >> password;

    ifstream fin("users.txt"); // sửa tên file cho đúng
    string line;
    bool found = false;

    while (getline(fin, line)) {
        istringstream iss(line);
        string u, p, raw;
        int admin, autoGen;

        getline(iss, u, ' ');
        getline(iss, p, '|');
        getline(iss, raw, '|');
        string name = raw;

        iss >> admin >> autoGen;

        if (u == username && p == hashPassword(password)) {
            found = true;
            cout << "Login successful.\n";
            if (autoGen)
                cout << "You must change your password now.\n";
            break;
        }
    }
    if (!found) cout << "Login failed.\n";
    fin.close();
}

int main() {
    int choice;
    do {
        cout << "\n--- MENU ---\n1. Register\n2. Login\n0. Exit\nChoice: ";
        cin >> choice;
        switch (choice) {
        case 1: registerUser(); break;
        case 2: loginUser(); break;
        case 0: cout << "Goodbye!\n"; break;
        default: cout << "Invalid choice!\n";
        }
    } while (choice != 0);
    return 0;
}
