#include "User.h"
#include <iostream>
#include <functional>

User::User() {}

User::User(string user, string pass, string name, bool admin, bool autoGen) {
	username = user;
	hashedPassword = hashPassword(pass);
	fullName = name;
	isAdmin = admin;
	isAutogeneratedPassword = autoGen;
}

void User::display() {
	cout << "Username: " << username << endl;
	cout << "Full Name: " << fullName << endl;
	cout << "Is Admin:" << (isAdmin ? "Yes" : "No") << endl;
}

bool User::verifyPassword(string inputPass) {
	hash<string> hasher;
	return hashPassword(inputPass) == hashedPassword;
}

string hashPassword(const string& password) {
	// Simple hash function for demonstration purposes
	hash<string> hasher;
	return to_string(hasher(password));
}

string genrateOTP() {
	srand(time(NULL));
	string otp;
	for (int i = 0; i < 6; ++i)
	{
		otp += to_string(rand() % 10); 
		return otp;
	}
}