#pragma once
#ifndef USER_H
#define USER_H

#include <string>
using namespace std;

class User {
public:
	string username;
	string hashedPassword;
	string fullName;
	bool isAdmin = false;
	bool isAutogeneratedPassword = false;

	User();
	User(string user, string pass, string name, bool admin = false, bool autoGen = false);
	void display();
	bool verifyPassword(string pass);
};

string hashPassword(const string& password);
string genrateOTP();

#endif 
