#include "login_system.h"
#include <iostream>
#include <limits>
#include <fstream>
#include <sstream>
using namespace std;

// Ghi OTP vào pending_change.txt
void logPendingChange(const std::string& username, const std::string& otp, const std::string& type) {
    std::ofstream fout("pending_change.txt", std::ios::app);
    time_t now = time(nullptr);
    fout << "Username: " << username << "\n";
    fout << "OTP: " << otp << "\n";
    fout << "Change: " << type << "\n";
    fout << "Time: " << nowToString(now) << "\n";
    fout << "-----------\n";
    fout.close();
}

void scheduleFullNameChange(User* u, vector<User>& users) {
    cout << "Enter new full name: ";
    string nm; getline(cin, nm);
    u->pendingFullName = nm;
    u->otp = genOTP();
    saveUsers(users);
    logPendingChange(u->username, u->otp, "FullName");
    cout << "Change scheduled! User must confirm with OTP at next login.\n";
}

void schedulePasswordChange(User* u, vector<User>& users) {
    cout << "Enter new password: ";
    string np = inputHiddenPassword();
    u->pendingPasswordHash = to_string(hashPassword(np));
    u->otp = genOTP();
    saveUsers(users);
    logPendingChange(u->username, u->otp, "Password");
    cout << "Change scheduled! User must confirm with OTP at next login.\n";
}

void changePassword(User* u, vector<User>& users) {
    if (!requireOTP(u->username)) return;
    cin.ignore(numeric_limits<streamsize>::max(), '\n');
    cout << "New password: ";
    string np = inputHiddenPassword();
    u->passwordHash = hashPassword(np);
    u->isAutoGenerated = false;
    saveUsers(users);
    cout << "Password changed successfully.\n";
}

void updateFullName(User* u, vector<User>& users) {
    if (!requireOTP(u->username)) return;
    cin.ignore(numeric_limits<streamsize>::max(), '\n');
    cout << "New full name: ";
    string nm; getline(cin, nm);
    u->fullName = nm;
    saveUsers(users);
    cout << "Full name updated successfully.\n";
}

void viewProfile(User* u) {
    cout << "--- Profile ---\n"
        << "Username   : " << u->username << "\n"
        << "Full name  : " << u->fullName << "\n"
        << "Wallet ID  : " << u->wallet.id << "\n"
        << "Balance    : " << (u->isAdmin ? "Unlimited" : to_string(u->wallet.balance)) << "\n";
}

void viewHistory(User* u) {
    cout << "--- Transaction History ---\n";
    for (auto& tx : u->wallet.history) {
        cout << nowToString(tx.timestamp) << " | "
            << tx.fromWallet << " -> " << tx.toWallet << " : " << tx.amount << "\n";
    }
}

void transferPoints(User* u, vector<User>& users) {
    cout << "Destination wallet ID: ";
    string dest; cin >> dest;
    User* v = nullptr;
    for (auto& x : users)
        if (x.wallet.id == dest) v = &x;
    if (!v) { cout << "Wallet not found.\n"; return; }
    cout << "Amount to transfer: ";
    int amt; cin >> amt;
    if (!u->isAdmin && u->wallet.balance < amt) { cout << "Insufficient balance.\n"; return; }
    if (!requireOTP(u->username)) return;
    if (!u->isAdmin) u->wallet.balance -= amt;
    v->wallet.balance += amt;
    Transaction tx{ u->wallet.id, v->wallet.id, amt, time(nullptr) };
    u->wallet.history.push_back(tx);
    v->wallet.history.push_back(tx);
    saveUsers(users);
    cout << "Transfer successful.\n";
}
