#include "login_system.h"
#include <iostream>
#include <limits>
using namespace std;

void changePassword(User* u, vector<User>& users) {
    if (!requireOTP(u->username)) return;
    cout << "New password: ";
    string np;
    np = inputHiddenPassword();
    u->passwordHash = hashPassword(np);
    u->isAutoGenerated = false;
    saveUsers(users);
    cout << "Password changed successfully.\n";
}

void viewProfile(User* u) {
    cout << "\n--- Profile ---\n"
        << "Username   : " << u->username << "\n"
        << "Full name  : " << u->fullName << "\n"
        << "Wallet ID  : " << u->wallet.id << "\n"
        << "Balance    : "
        << (u->isAdmin ? "Unlimited" : to_string(u->wallet.balance))
        << "\n";
}

void updateFullName(User* u, vector<User>& users) {
    if (!requireOTP(u->username)) return;
    cin.ignore(numeric_limits<streamsize>::max(), '\n');
    cout << "New full name: ";
    string nm;
    getline(cin, nm);
    u->fullName = nm;
    saveUsers(users);
    cout << "Name updated successfully.\n";
}

void viewHistory(User* u) {
    cout << "\n--- Transaction History ---\n";
    for (const auto& tx : u->wallet.history) {
        cout << nowToString(tx.timestamp)
            << " | " << tx.fromWallet
            << " -> " << tx.toWallet
            << " : " << tx.amount << "\n";
    }
}

void transferPoints(User* u, vector<User>& users) {
    cout << "Destination wallet ID: ";
    string destWalletId;
    cin >> destWalletId;

    User* v = nullptr;
    for (auto& x : users)
        if (x.wallet.id == destWalletId) {
            v = &x; break;
        }
    if (!v) {
        cout << "Wallet not found.\n";
        return;
    }

    cout << "Amount to transfer: ";
    int amt;
    cin >> amt;

    if (!u->isAdmin && u->wallet.balance < amt) {
        cout << "Insufficient balance.\n";
        return;
    }
    if (!requireOTP(u->username)) return;

    if (!u->isAdmin)
        u->wallet.balance -= amt;
    v->wallet.balance += amt;

    Transaction tx{ u->wallet.id, v->wallet.id, amt, time(nullptr) };
    u->wallet.history.push_back(tx);
    v->wallet.history.push_back(tx);
    saveUsers(users);
    cout << "Transfer successful.\n";
}
