#include "login_system.h"
#include <fstream>
#include <iostream>
#include <limits>
using namespace std;

static constexpr size_t MAX_USERS = 1000000;
static constexpr size_t MAX_TXNS = 100000;

const string DATA_FILE = "users.dat";
const string BACKUP_FILE = "users.bak";

void backupData() {
    ifstream src(DATA_FILE);
    ofstream dst(BACKUP_FILE);
    if (!src || !dst) {
        cerr << "Failed to open data/backup file for copying.\n";
        return;
    }
    dst << src.rdbuf();
}

vector<User> loadUsers() {
    vector<User> users;
    ifstream fin(DATA_FILE);
    if (!fin) return users;

    size_t n = 0;
    if (!(fin >> n) || n > MAX_USERS) {
        cerr << "Error: invalid user count.\n";
        return users;
    }
    users.reserve(n);

    for (size_t i = 0; i < n; ++i) {
        User u;
        size_t m = 0;
        if (!(fin >> u.username
            >> u.passwordHash
            >> u.fullName
            >> u.isAdmin
            >> u.isAutoGenerated
            >> u.wallet.id
            >> u.wallet.balance)) {
            cerr << "Error: malformed user entry at index " << i << ".\n";
            break;
        }
        if (!(fin >> m) || m > MAX_TXNS) {
            m = 0;
        }
        u.wallet.history.reserve(m);
        for (size_t j = 0; j < m; ++j) {
            Transaction tx;
            if (!(fin >> tx.fromWallet
                >> tx.toWallet
                >> tx.amount
                >> tx.timestamp)) {
                cerr << "Warning: malformed txn #" << j
                    << " for user " << u.username << ".\n";
                break;
            }
            u.wallet.history.push_back(tx);
        }
        users.push_back(move(u));
    }
    return users;
}

void saveUsers(const vector<User>& users) {
    ofstream fout(DATA_FILE);
    if (!fout) {
        cerr << "Cannot open data file for writing.\n";
        return;
    }
    fout << users.size() << "\n";
    for (const auto& u : users) {
        fout << u.username << " "
            << u.passwordHash << " "
            << u.fullName << " "
            << u.isAdmin << " "
            << u.isAutoGenerated << " "
            << u.wallet.id << " "
            << u.wallet.balance << "\n";
        fout << u.wallet.history.size() << "\n";
        for (const auto& tx : u.wallet.history) {
            fout << tx.fromWallet << " "
                << tx.toWallet << " "
                << tx.amount << " "
                << tx.timestamp << "\n";
        }
    }
}
