#include "login_system.h"
#include <iostream>
#include <limits>
using namespace std;

int main() {
    backupData();
    auto users = loadUsers();

    // --- Ensure default admin exists ---
    if (!findUser(users, "admin")) {
        User a;
        a.username = "admin";
        a.passwordHash = hashPassword("admin");
        a.fullName = "Administrator";
        a.isAdmin = true;
        a.isAutoGenerated = false;
        a.wallet.id = "WAL" + to_string(time(nullptr));
        a.wallet.balance = -1;    // unlimited
        users.push_back(a);
        saveUsers(users);
        cout << "Default admin created: admin / admin\n";
    }
    // --- End default admin ---

    while (true) {
        clearScreen();
        cout << "=== SYSTEM MENU ===\n"
            << "1. Register    2. Login    0. Exit\n"
            << "Choice: ";
        int cmd;
        cin >> cmd;
        cin.ignore(numeric_limits<streamsize>::max(), '\n');

        switch (cmd) {
        case 1:
            registerUser(users);
            break;
        case 2:
            if (User* u = login(users)) {
                if (u->isAdmin)
                    adminMenu(u, users);
                else
                    userMenu(u, users);
            }
            break;
        case 0:
            cout << "Goodbye.\n";
            return 0;
        default:
            cout << "Invalid choice.\n";
        }

        cout << "\nPress Enter to return to main menu...";
        cin.get();
    }
    return 0;
}
